[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "openECCI"
authors = [{name = "Zhou XU", email = "zhou.xu@monash.edu"}]
dynamic = ["version", "description"]
